<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Corporate Financial Operational Audit Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
        .header { text-align: center; border-b: 3px double #333; padding-bottom: 20px; margin-bottom: 30px; }
        .meta { display: flex; justify-content: space-between; font-size: 12px; font-weight: bold; margin-bottom: 20px; }
        table { w: 100%; width: 100%; border-collapse: collapse; margin-bottom: 30px; text-align: left; }
        th, td { padding: 12px; border: 1px solid #ddd; font-size: 14px; }
        th { background: #f4f4f4; text-transform: uppercase; font-size: 11px; }
        .footer { text-align: center; margin-top: 50px; font-size: 11px; border-top: 1px solid #ccc; padding-top: 10px; }
        @media print { .no-print { display: none; } }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 20px; text-align: right;">
        <button onclick="window.print();" style="padding: 10px 20px; background: #000; color: #fff; font-weight: bold; border: none; cursor: pointer;">Execute Print Device Link</button>
    </div>

    <div class="header">
        <h1>Grand Hotel Systems Audit Report</h1>
        <p>Administrative Core Performance Intelligence Records Ledger</p>
    </div>

    <div class="meta">
        <div>GENERATED BY: System Administrative Node</div>
        <div>DATE STAMP: <?php echo date('Y-m-d H:i:s'); ?></div>
    </div>

    <h3>Financial Allocation Ledger Summaries</h3>
    <table>
        <thead>
            <tr><th>Performance Criteria Category</th><th>Accumulated Calculation Values</th></tr>
        </thead>
        <tbody>
            <tr><td>Gross Base Room Accommodations Earnings</td><td>$<?php echo number_format($reports['extras']['base'] ?? 0, 2); ?></td></tr>
            <tr><td>Ancillary Extra Support Services Charges</td><td>$<?php echo number_format($reports['extras']['service'] ?? 0, 2); ?></td></tr>
            <tr><td>Authorized Promotional Customer Discounts Deductions</td><td>-$<?php echo number_format($reports['extras']['discounts'] ?? 0, 2); ?></td></tr>
        </tbody>
    </table>

    <div class="footer">
        Confidential Internal Corporate Performance Ledger Matrix. Document output tracking active.
    </div>
</body>
</html>